// <auto-generated />
namespace VendingMachine.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class STEPOneSeperateMachineFromAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(STEPOneSeperateMachineFromAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201311222143569_STEPOneSeperateMachineFromAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
