// <auto-generated />
namespace VendingMachine.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StepTwoSeperateMachineFromAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StepTwoSeperateMachineFromAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201311222235048_StepTwoSeperateMachineFromAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
