// <auto-generated />
namespace VendingMachine.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StepOneAddTwitterAccountLogins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StepOneAddTwitterAccountLogins));
        
        string IMigrationMetadata.Id
        {
            get { return "201311221937322_StepOneAddTwitterAccountLogins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
