// <auto-generated />
namespace VendingMachine.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Step2SeperateTwitterAccountFromMachines : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Step2SeperateTwitterAccountFromMachines));
        
        string IMigrationMetadata.Id
        {
            get { return "201311222059385_Step2SeperateTwitterAccountFromMachines"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
